### ISSUE TITLE
 TypeError: this.getValue is not a function

### ISSUE THREAD

**Issue by aziotdev** [alexsk/mongoose-intl#25] opened 2019-07-01 15:17 UTC
I tried the example given,

it results

{ title:
      { CastError: Cast to String failed for value "{ en: 'Title on default language',
        de: 'Another German title',
        fr: 'French title' }" at path "title"

**Comment by alexsk** [comment] 2019-07-02 22:07
Duplicate of #20

**Closed as completed by alexsk** 2019-07-02 22:07 UTC
